name: Nightly

on:
  schedule:
    - cron:  '0 0 * * *'

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       versions:
         - IMAGE: rodolpheche/wiremock:nightly
           CONTEXT: .
         - IMAGE: rodolpheche/wiremock:nightly-alpine
           CONTEXT: alpine
    steps:

    - name: Checkout sources
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Update version if newer
      run: |
        CURRENT_VERSION=$(git describe --abbrev=0 --tags)
        LATEST_VERSION=$(git -c 'versionsort.suffix=-' ls-remote --tags --sort='v:refname' git://github.com/tomakehurst/wiremock.git '*.*.*' | tail -1 | cut -d '/' -f3)
        if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]
        then
          sed -i s/${CURRENT_VERSION}/${LATEST_VERSION}/g Dockerfile alpine/Dockerfile
        fi

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Wiremock Docker image
      run: docker build -t ${{ matrix.versions.IMAGE }} ${{ matrix.versions.CONTEXT }}

    - name: Test Wiremock Docker image
      run: |
        # default
        docker container run -d --name test -p 8080:8080 ${{ matrix.versions.IMAGE }}
        timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/; do sleep 1; done'
        docker container rm -f test

        # args
        docker container run -d --name test -p 8443:8443 ${{ matrix.versions.IMAGE }} --https-port 8443
        timeout 10 bash -c 'while ! curl --fail --insecure https://localhost:8443/__admin/; do sleep 1; done'
        docker container rm -f test

        if [ "${{ matrix.versions.CONTEXT }}" != "alpine" ]
        then
          # helloworld
          docker build -t wiremock-hello samples/hello
          docker container run -d --name test -p 8080:8080 wiremock-hello
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/hello; do sleep 1; done'
          docker container rm -f test

          # random
          docker build -t wiremock-random samples/random
          docker container run -d --name test -p 8080:8080 wiremock-random
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/random; do sleep 1; done'
          docker container rm -f test
        fi

    - name: Push Wiremock Docker image to Docker HUB
      run: docker push ${{ matrix.versions.IMAGE }}

  check-new-version:
    runs-on: ubuntu-latest
    needs: [ci]
    outputs:
      new_version: ${{ steps.new_version.outputs.NEW_VERSION }}
    steps:

    - name: Checkout sources
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Release if newer version
      run: |
        CURRENT_VERSION=$(git describe --abbrev=0 --tags)
        LATEST_VERSION=$(git -c 'versionsort.suffix=-' ls-remote --tags --sort='v:refname' git://github.com/tomakehurst/wiremock.git '*.*.*' | tail -1 | cut -d '/' -f3)
        if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]
        then
          echo "::set-output name=NEW_VERSION::$LATEST_VERSION"
        fi
      id: new_version

  docker-push:
    runs-on: ubuntu-latest
    needs: [check-new-version]
    if: needs.check-new-version.outputs.new_version
    strategy:
      matrix:
       versions:
         - FROM_IMAGE: rodolpheche/wiremock:nightly
           TO_IMAGE: rodolpheche/wiremock:latest
         - FROM_IMAGE: rodolpheche/wiremock:nightly
           TO_IMAGE: rodolpheche/wiremock:${{ needs.check-new-version.outputs.new_version }}
         - FROM_IMAGE: rodolpheche/wiremock:nightly-alpine
           TO_IMAGE: rodolpheche/wiremock:latest-alpine
         - FROM_IMAGE: rodolpheche/wiremock:nightly-alpine
           TO_IMAGE: rodolpheche/wiremock:${{ needs.check-new-version.outputs.new_version }}-alpine
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Release Wiremock Docker image
      run: |
        docker pull ${{ matrix.versions.FROM_IMAGE }}
        docker tag ${{ matrix.versions.FROM_IMAGE }} ${{ matrix.versions.TO_IMAGE }}
        docker push ${{ matrix.versions.TO_IMAGE }}

  release:
    runs-on: ubuntu-latest
    needs: [docker-push, check-new-version]
    steps:

    - name: Checkout sources
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Update version
      run: |
        LAST_VERSION=$(git describe --tag --abbrev=0)
        LAST_MINOR_VERSION=${LAST_VERSION%.*}
        NEW_VERSION=${{ needs.check-new-version.outputs.new_version }}
        NEW_MINOR_VERSION=${NEW_VERSION%.*}
        sed -i s/${LAST_VERSION}/${NEW_VERSION}/g readme.md Dockerfile alpine/Dockerfile
        sed -i s/${LAST_MINOR_VERSION}/${NEW_MINOR_VERSION}/g readme.md
        git config --local user.name "rodolpheche"
        git config --local user.email "rodolphe.chaigneau@gmail.com"
        git add .
        git commit -m "upgrade to version $NEW_VERSION"
        git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/rodolpheche/wiremock-docker.git
        git push origin main

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.check-new-version.outputs.new_version }}
