name: One Shot GH action to transfert images from old Docker Hub account to new one

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       versions:
         - VERSION: 2.0.6-beta
         - VERSION: 2.0.10-beta
         - VERSION: 2.1.0-beta
         - VERSION: 2.1.6
         - VERSION: 2.1.7
         - VERSION: 2.1.11
         - VERSION: 2.1.12
         - VERSION: 2.2.1
         - VERSION: 2.2.2
         - VERSION: 2.3.1
         - VERSION: 2.4.1
         - VERSION: 2.5.0
         - VERSION: 2.5.1
         - VERSION: 2.6.0
         - VERSION: 2.6.0-alpine
         - VERSION: 2.7.0
         - VERSION: 2.7.0-alpine
         - VERSION: 2.7.1
         - VERSION: 2.7.1-alpine
         - VERSION: 2.8.0
         - VERSION: 2.8.0-alpine
         - VERSION: 2.9.0
         - VERSION: 2.9.0-alpine
         - VERSION: 2.10.0
         - VERSION: 2.10.0-alpine
         - VERSION: 2.10.1
         - VERSION: 2.10.1-alpine
         - VERSION: 2.11.0
         - VERSION: 2.11.0-alpine
         - VERSION: 2.12.0
         - VERSION: 2.12.0-alpine
         - VERSION: 2.13.0
         - VERSION: 2.13.0-alpine
         - VERSION: 2.14.0
         - VERSION: 2.14.0-alpine
         - VERSION: 2.15.0
         - VERSION: 2.15.0-alpine
         - VERSION: 2.16.0
         - VERSION: 2.16.0-alpine
         - VERSION: 2.17.0
         - VERSION: 2.17.0-alpine
         - VERSION: 2.18.0
         - VERSION: 2.18.0-alpine
         - VERSION: 2.19.0
         - VERSION: 2.19.0-alpine
         - VERSION: 2.20.0
         - VERSION: 2.20.0-alpine
         - VERSION: 2.21.0
         - VERSION: 2.21.0-alpine
         - VERSION: 2.22.0
         - VERSION: 2.22.0-alpine
         - VERSION: 2.23.0
         - VERSION: 2.23.0-alpine
         - VERSION: 2.23.2
         - VERSION: 2.23.2-alpine
         - VERSION: 2.24.0
         - VERSION: 2.24.0-alpine
         - VERSION: 2.24.1
         - VERSION: 2.24.1-alpine
         - VERSION: 2.25.0
         - VERSION: 2.25.0-alpine
         - VERSION: 2.25.1
         - VERSION: 2.25.1-alpine
         - VERSION: 2.26.0
         - VERSION: 2.26.0-alpine
         - VERSION: 2.26.1
         - VERSION: 2.26.1-alpine
         - VERSION: 2.26.2
         - VERSION: 2.26.2-alpine
         - VERSION: 2.26.3
         - VERSION: 2.26.3-alpine
         - VERSION: 2.27.0
         - VERSION: 2.27.0-alpine
         - VERSION: 2.27.1
         - VERSION: 2.27.1-alpine
         - VERSION: 2.27.2
         - VERSION: 2.27.2-alpine
         - VERSION: 2.28.0
         - VERSION: 2.28.0-alpine
         - VERSION: 2.28.1
         - VERSION: 2.28.1-alpine
         - VERSION: 2.29.0
         - VERSION: 2.29.0-alpine
         - VERSION: 2.29.1
         - VERSION: 2.29.1-alpine
         - VERSION: 2.30.0
         - VERSION: 2.30.0-alpine
         - VERSION: 2.30.1
         - VERSION: 2.30.1-alpine
         - VERSION: 2.31.0
         - VERSION: 2.31.0-alpine
         - VERSION: latest
         - VERSION: latest-alpine
         - VERSION: nightly
         - VERSION: nightly-alpine
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: wiremock
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Transfert Wiremock Docker image to new Docker HUB account
      run: |
        docker pull rodolpheche/wiremock:${{ matrix.versions.VERSION }}
        docker tag rodolpheche/wiremock:${{ matrix.versions.VERSION }} wiremock/wiremock:${{ matrix.versions.VERSION }}
        docker push wiremock/wiremock:${{ matrix.versions.VERSION }}
